// Code generated by reflexive_interface_generator -type=MyService; DO NOT EDIT.

package example

import "io"

// IMyService is an interface that mirrors all methods of MyService.
type IMyService interface {
	GetName() string
	SetName(name string)
	Increment() int
	Process(data []byte) ([]byte, error)
	Write(p []byte) (n int, err error)
	ReadFrom(r io.Reader) (int64, error)
}

// Compile-time check that MyService implements IMyService.
var _ IMyService = (*MyService)(nil)
