// Code generated by "stringer -type=RemoteConnectionType"; DO NOT EDIT.

package repo

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RemoteConnectionTypeUnspecified-0]
	_ = x[RemoteConnectionTypeNativeDotenvXDG-1]
	_ = x[RemoteConnectionTypeSocketUnix-2]
	_ = x[RemoteConnectionTypeUrl-3]
	_ = x[RemoteConnectionTypeStdioLocal-4]
	_ = x[RemoteConnectionTypeStdioSSH-5]
	_ = x[_RemoteConnectionTypeMax-6]
}

const _RemoteConnectionType_name = "RemoteConnectionTypeUnspecifiedRemoteConnectionTypeNativeDotenvXDGRemoteConnectionTypeSocketUnixRemoteConnectionTypeUrlRemoteConnectionTypeStdioLocalRemoteConnectionTypeStdioSSH_RemoteConnectionTypeMax"

var _RemoteConnectionType_index = [...]uint8{0, 31, 66, 96, 119, 149, 177, 201}

func (i RemoteConnectionType) String() string {
	if i < 0 || i >= RemoteConnectionType(len(_RemoteConnectionType_index)-1) {
		return "RemoteConnectionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RemoteConnectionType_name[_RemoteConnectionType_index[i]:_RemoteConnectionType_index[i+1]]
}
