// Code generated by "stringer -type=copyResultState"; DO NOT EDIT.

package blob_stores

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CopyResultStateUnknown-0]
	_ = x[CopyResultStateSuccess-1]
	_ = x[CopyResultStateNilRemoteBlobStore-2]
	_ = x[CopyResultStateMissingLocally-3]
	_ = x[CopyResultStateExistsLocally-4]
	_ = x[CopyResultStateExistsLocallyAndRemotely-5]
	_ = x[CopyResultStateError-6]
}

const _copyResultState_name = "CopyResultStateUnknownCopyResultStateSuccessCopyResultStateNilRemoteBlobStoreCopyResultStateMissingLocallyCopyResultStateExistsLocallyCopyResultStateExistsLocallyAndRemotelyCopyResultStateError"

var _copyResultState_index = [...]uint8{0, 22, 44, 77, 106, 134, 173, 193}

func (i copyResultState) String() string {
	if i < 0 || i >= copyResultState(len(_copyResultState_index)-1) {
		return "copyResultState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _copyResultState_name[_copyResultState_index[i]:_copyResultState_index[i+1]]
}
