// Code generated by "stringer -type=RemoteConnection"; DO NOT EDIT.

package repo

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RemoteConnectionUnspecified-0]
	_ = x[RemoteConnectionNative-1]
	_ = x[RemoteConnectionNativeLocalOverridePath-2]
	_ = x[RemoteConnectionSocketUnix-3]
	_ = x[RemoteConnectionUrl-4]
	_ = x[RemoteConnectionStdioLocal-5]
	_ = x[RemoteConnectionStdioSSH-6]
	_ = x[_RemoteConnectionMax-7]
}

const _RemoteConnection_name = "RemoteConnectionUnspecifiedRemoteConnectionNativeRemoteConnectionNativeLocalOverridePathRemoteConnectionSocketUnixRemoteConnectionUrlRemoteConnectionStdioLocalRemoteConnectionStdioSSH_RemoteConnectionMax"

var _RemoteConnection_index = [...]uint8{0, 27, 49, 88, 114, 133, 159, 183, 203}

func (i RemoteConnection) String() string {
	if i < 0 || i >= RemoteConnection(len(_RemoteConnection_index)-1) {
		return "RemoteConnection(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RemoteConnection_name[_RemoteConnection_index[i]:_RemoteConnection_index[i+1]]
}
