// Code generated by "stringer -type=location"; DO NOT EDIT.

package blob_store_id

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LocationTypeUnknown-0]
	_ = x[LocationTypeXDG-1]
	_ = x[LocationTypeOverride-2]
	_ = x[LocationTypeRemote-3]
}

const _location_name = "LocationTypeUnknownLocationTypeXDGLocationTypeOverrideLocationTypeRemote"

var _location_index = [...]uint8{0, 19, 34, 54, 72}

func (i location) String() string {
	if i < 0 || i >= location(len(_location_index)-1) {
		return "location(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _location_name[_location_index[i]:_location_index[i+1]]
}
