// Code generated by "stringer -type=copyResultState"; DO NOT EDIT.

package blob_stores

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CopyResultStateUnknown-0]
	_ = x[CopyResultStateSuccess-1]
	_ = x[CopyResultStateMissingLocally-2]
	_ = x[CopyResultStateExistsLocally-3]
	_ = x[CopyResultStateExistsLocallyAndRemotely-4]
	_ = x[CopyResultStateError-5]
}

const _copyResultState_name = "CopyResultStateUnknownCopyResultStateSuccessCopyResultStateMissingLocallyCopyResultStateExistsLocallyCopyResultStateExistsLocallyAndRemotelyCopyResultStateError"

var _copyResultState_index = [...]uint8{0, 22, 44, 73, 101, 140, 160}

func (i copyResultState) String() string {
	if i < 0 || i >= copyResultState(len(_copyResultState_index)-1) {
		return "copyResultState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _copyResultState_name[_copyResultState_index[i]:_copyResultState_index[i+1]]
}
