// Code generated by "stringer -type=Type"; DO NOT EDIT.

package remote_connection_types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeUnspecified-0]
	_ = x[TypeNative-1]
	_ = x[TypeNativeLocalOverridePath-2]
	_ = x[TypeSocketUnix-3]
	_ = x[TypeUrl-4]
	_ = x[TypeStdioLocal-5]
	_ = x[TypeStdioSSH-6]
	_ = x[_TypeMax-7]
}

const _Type_name = "TypeUnspecifiedTypeNativeTypeNativeLocalOverridePathTypeSocketUnixTypeUrlTypeStdioLocalTypeStdioSSH_TypeMax"

var _Type_index = [...]uint8{0, 15, 25, 52, 66, 73, 87, 99, 107}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
